dist: bionic
language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: SETUP=lowest
        - php: 7.3
          env: SETUP=lowest
        - php: 7.4
          env: SETUP=lowest

before_install:
    - travis_retry composer self-update

install:
    - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
    - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
    - vendor/bin/phpunit

notifications:
    email: false
